import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

/* ==========================================================================
   TYPE DEFINITIONS
   ========================================================================== */

// Which category a notification belongs to (drives the filter tabs)
type NotificationCategory = 'Alerts' | 'Approvals' | 'Bookings' | 'General';

// Which icon + accent color to use for a notification row
type NotificationIconType = 'person' | 'approval' | 'booking' | 'transfer' | 'warning' | 'danger';

// Shape of a single notification/activity log entry
interface NotificationItem {
  id: string;
  icon: NotificationIconType;
  category: NotificationCategory;
  // titleParts lets us bold/color specific words within the title line
  // (e.g. the asset tag, or a person's name) while keeping the rest plain.
  titleParts: { text: string; style?: 'bold' | 'link' }[];
  detail: string;
  detailTone?: 'muted' | 'warning'; // 'warning' renders the detail line in amber italics
  timeAgo: string;
}

/**
 * Notifications & Activity Logs page.
 * Shows a filterable feed of system/asset/booking events with a
 * "mark all as read" and "export logs" action pair.
 */
@Component({
  selector: 'app-notifications',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './notifications.html',
  styleUrls: ['./notifications.css'],
})
export class NotificationsComponent {
  /* ------------------------------------------------------------------------
     MOCK DATA
     In a real app this would come from a service/API call instead of being
     hardcoded on the component.
     ------------------------------------------------------------------------ */
  notifications: NotificationItem[] = [
    {
      id: 'notif-1',
      icon: 'person',
      category: 'General',
      titleParts: [
        { text: 'Laptop ' },
        { text: 'AF-0014', style: 'bold' },
        { text: ' assigned to ' },
        { text: 'Priya Shah', style: 'link' },
      ],
      detail: 'Asset successfully checked out',
      timeAgo: '2m ago',
    },
    {
      id: 'notif-2',
      icon: 'approval',
      category: 'Approvals',
      titleParts: [
        { text: 'Maintenance request ' },
        { text: 'AF-0055', style: 'bold' },
        { text: ' approved' },
      ],
      detail: 'Scheduled for next Monday at 10:00 AM',
      timeAgo: '18m ago',
    },
    {
      id: 'notif-3',
      icon: 'booking',
      category: 'Bookings',
      titleParts: [
        { text: 'Booking confirmed : ' },
        { text: 'Room B2', style: 'link' },
        { text: ' : 2:00 to 3:00 PM' },
      ],
      detail: 'Calendar invite sent to attendees',
      timeAgo: '1h ago',
    },
    {
      id: 'notif-4',
      icon: 'transfer',
      category: 'Approvals',
      titleParts: [
        { text: 'Transfer approved : ' },
        { text: 'AF-0033', style: 'bold' },
        { text: ' to facilities dept' },
      ],
      detail: 'Approved by Administration',
      timeAgo: '3h ago',
    },
    {
      id: 'notif-5',
      icon: 'warning',
      category: 'Alerts',
      titleParts: [
        { text: 'Overdue return : ' },
        { text: 'AF-0021', style: 'bold' },
        { text: ' was due 3 days ago' },
      ],
      detail: 'High Priority Action Required',
      detailTone: 'warning',
      timeAgo: '1d ago',
    },
    {
      id: 'notif-6',
      icon: 'danger',
      category: 'Alerts',
      titleParts: [
        { text: 'Audit discrepancy flagged : ' },
        { text: 'AF-0088', style: 'bold' },
        { text: ' damaged' },
      ],
      detail: 'Incident report generated by Security',
      timeAgo: '2d ago',
    },
  ];

  /** Which filter tab is currently selected. */
  activeFilter: 'All' | NotificationCategory = 'All';

  /** Rows to display, filtered by the active tab. */
  get filteredNotifications(): NotificationItem[] {
    if (this.activeFilter === 'All') return this.notifications;
    return this.notifications.filter((n) => n.category === this.activeFilter);
  }

  /* ------------------------------------------------------------------------
     EVENT HANDLERS
     ------------------------------------------------------------------------ */

  setFilter(filter: 'All' | NotificationCategory): void {
    this.activeFilter = filter;
    console.log(`Filter changed to: ${filter}`);
  }

  onMarkAllAsRead(): void {
    console.log('Action: mark all notifications as read');
  }

  onExportLogs(): void {
    console.log('Action: export activity logs');
  }

  onViewOlderActivity(): void {
    console.log('Action: load older activity');
  }

  /**
   * Placeholder for sidebar nav clicks. If your app already has a shared
   * layout/shell component handling navigation, delete the sidebar markup
   * from notifications.html entirely and remove this method.
   */
  onNavClick(page: string): void {
    console.log(`Navigated to: ${page}`);
  }
}